version: '3'
services:
  iis-webapp:
    image: iis-webapp
    container_name: iis-webapp
    env_file: 
      - ./enviroment/database_user.env
    build:
      context: .
      dockerfile: Dockerfile-webapp
    ports:
    - "6969:6969"
  iis-database:
    image: iis-database
    container_name: iis-database
    build:
      context: .
      dockerfile: Dockerfile-database
    ports:
    - "5432:5432"
    volumes:
      - /var/lib/pgsql/data
